* Package management

** Set package archives

Add MELPA/ELPA/Non-GNU/ELPA-dev to package archives.

#+begin_src emacs-lisp
  (require 'package)

  (setq package-archives
        '(("melpa" . "https://melpa.org/packages/")
          ("elpa" . "https://elpa.gnu.org/packages/")
          ("nongnu" . "https://elpa.nongnu.org/nongnu/")
          ("elpa-devel" . "https://elpa.gnu.org/devel/")))

  ;; Initialize the packages, avoiding a re-initialization.

  (unless (bound-and-true-p package--initialized)
    (package-initialize))
#+end_src

** Setup use-package

#+begin_src emacs-lisp
;; Make sure `use-package' is available.

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; Configure `use-package' prior to loading it.

(eval-and-compile
  (setq use-package-always-ensure nil)
  (setq use-package-always-defer nil)
  (setq use-package-always-demand nil)
  (setq use-package-expand-minimally nil)
  (setq use-package-enable-imenu-support t)
  (setq use-package-compute-statistics nil)
  ;; The following is VERY IMPORTANT.  Write hooks using their real name
  ;; instead of a shorter version: after-init ==> `after-init-hook'.
  ;;
  ;; This is to empower help commands with their contextual awareness,
  ;; such as `describe-symbol'.
  (setq use-package-hook-name-suffix nil))

(eval-when-compile
  (require 'use-package))

(use-package diminish :ensure t :after use-package) ;; if you use :diminish
(use-package bind-key :ensure t :after use-package) ;; if you use any :bind variant
(use-package delight :ensure t :after use-package)  ;; Use delighting for modes
#+end_src
* Default settings 

#+begin_src emacs-lisp
(setq-default cursor-type 'bar)               ; Line-style cursor similar to other text editors
(setq inhibit-startup-screen t)               ; Disable startup screen
(setq initial-scratch-message "")	        ; Make *scratch* buffer blank
(setq-default frame-title-format '("%b"))     ; Make window title the buffer name
(setq confirm-kill-processes nil)		; Stop confirming the killing of processes
(setq use-short-answers t)                    ; y-or-n-p makes answering questions faster
(show-paren-mode t)                           ; Visually indicates pair of matching parentheses
(delete-selection-mode t)                     ; Start writing straight after deletion
(put 'narrow-to-region 'disabled nil)	        ; Allows narrowing bound to C-x n n (region) and C-x n w (widen)
(setq read-process-output-max (* 1024 1024))  ; Increase the amount of data which Emacs reads from the process
(global-hl-line-mode 1)			; Highlight the current line to make it more visible
(global-display-line-numbers-mode t)          ; Enable line numbers
(setq display-line-numbers-type 'relative)    ; Set relative line numbers
(setq create-lockfiles nil)                   ; lock files kill `npm start'
(setq-default fill-column 79)		        ; Set fill column to 80 rather than 70, in all cases.
(pixel-scroll-precision-mode 1)	        ; Precision scrolling
(setq ring-bell-function 'ignore)		; Disable bell sound
(setq-default indent-tabs-mode nil)		; Don't use tabs for indentation
(setq use-default-font-for-symbols nil)       ; Don't use use default fonts for symbols

;; Change locations of backups, autosaves and manual customizations
(setq backup-directory-alist `(("." . "~/.saves")))
(setq auto-save-file-name-transforms `((".*", "~/.saves/" t)))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
#+end_src

** Garbage collection

#+begin_src emacs-lisp
(use-package gcmh
  :ensure t
  :diminish gcmh-mode
  :custom
  (gcmh-mode 1)
  (gcmh-idle-delay 5)
  (gcmh-high-cons-threshold (* 16 1024 1024))
  (gc-cons-percentage 0.1))
#+end_src

** Useful packages

#+begin_src emacs-lisp
(use-package eldoc
  :delight eldoc-mode
  :custom
  (eldoc-echo-area-use-multiline-p nil))

(use-package autorevert
  :defer 2
  :delight auto-revert-mode
  :custom
  (auto-revert-use-notify nil))

(use-package recentf
  :defer 2
  :init
  (recentf-mode 1))

(use-package undo-tree
  :ensure t
  :init
  (setq undo-tree-auto-save-history nil)
  (global-undo-tree-mode))

(use-package helpful
  :ensure t
  :commands (helpful-callable helpful-variable helpful-command helpful-key)
  :bind
  ([remap describe-function] . helpful-function)
  ([remap describe-command] . helpful-command)
  ([remap describe-variable] . helpful-variable)
  ([remap describe-key] . helpful-key))

(use-package hydra
  :ensure t)
#+end_src

** OS specific settings

*** Define booleans for OS

#+begin_src emacs-lisp
(setq duy/is-macos
      (string= system-type "darwin"))

(setq duy/is-wsl
      (and (eq system-type 'gnu/linux)
           (string-match "WSL" operating-system-release)))
#+end_src

** MacOS specific settings

Set cmd as meta-key (to align with Windows/Linux location), and set option as super-key.

#+begin_src emacs-lisp
(when duy/is-macos
  (setq mac-command-modifier 'meta
        mac-option-modifier 'super))
#+end_src

** Windows/WSL specific settings

*** Browse URL with Microsoft Edge

#+begin_src emacs-lisp
(when duy/is-wsl  
  (defun browse-url-edge (url &optional _new-window)
    "Browse url with Microsoft Edge."
    (interactive (browse-url-interactive-arg "URL: "))
    (setq url (browse-url-encode-url url))
    (shell-command
     (concat "msedge " url))))
#+end_src

*** Open file with native Windows app

#+begin_src emacs-lisp
(when duy/is-wsl  
(defun duy/open-file-with-wsl (file &optional _new-window)
  "Open file with native Windows app."
  (interactive "fOpen with Windows app: ")
  (shell-command
   (concat "wslview '" file "'"))))
#+end_src

*** Prevent Windows intercepting certain hotkeys

See: https://emacs.stackexchange.com/questions/71706/blocked-keys-how-can-i-get-emacs-to-see-all-keystrokes

Note: after a restart of my WSL computer, =C-M-/= seems to work again. 

** Maximise window on startup

Don't maximise window on WSL (it doesn't work well as the X server does not recognize correct size of monitor).

#+begin_src emacs-lisp
(unless duy/is-wsl
        (add-to-list 'default-frame-alist '(fullscreen . maximized)))
#+end_src

* Evil keybindings (general)

** Evil

The Evil package(s) enable Vim-like keybindings.

#+begin_src emacs-lisp
(use-package evil
  :ensure t
  :init      ;; tweak evil's configuration before loading it
  (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
  (setq evil-want-keybinding nil)
  (setq evil-want-C-u-scroll t)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (setq evil-want-C-i-jump nil)
  (setq evil-disable-insert-state-bindings t)  ; don't use any of these: https://github.com/noctuid/evil-guide#switching-between-evil-and-emacs
  :config
  (evil-mode)
  (evil-set-undo-system 'undo-tree)
  ;; Use visual line motions (e.g. for when a long line is wrapped)
  (evil-global-set-key 'motion "j" 'evil-next-visual-line)
  (evil-global-set-key 'motion "k" 'evil-previous-visual-line)
  (global-set-key (kbd "C-M-u") 'universal-argument))
#+end_src

Evil collection is a collection of Evil bindings for the parts of Emacs that Evil does not cover properly by default.

#+begin_src emacs-lisp
(use-package evil-collection
  :ensure t
  :after evil
  :config
  (setq evil-collection-mode-list '(flymake
                                    xref
                                    vterm
                                    dashboard
                                    dired
                                    ibuffer
                                    magit
                                    pdf
                                    doc-view
                                    company
                                    embark
                                    helpful)) ; Modes to activate Evil keybindings for
  (evil-collection-init))
#+end_src

Bind kj in insert mode to ESC.

#+begin_src emacs-lisp
(use-package evil-escape
  :ensure t
  :init
  (evil-escape-mode 1)
  (setq evil-escape-key-sequence "kj")
  (setq evil-escape-delay 0.2))
#+end_src

Evil nerd commenter for line comment.

#+begin_src emacs-lisp
(use-package evil-nerd-commenter
  :ensure t
  :bind (("C-'" . evilnc-comment-or-uncomment-lines)
         ("C-," . evilnc-comment-or-uncomment-lines)
  :map org-mode-map)
  ("C-'" . nil))
#+end_src


Evil-org adds evil bindings to org-agenda.

#+begin_src emacs-lisp

(use-package evil-org
  :ensure t
  :after org
  :hook (org-mode . (lambda () evil-org-mode))
  :config
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))

#+end_src

evil-surround enables surrounding of (Vim) text objects (e.g. brackets or quotes)

#+begin_src emacs-lisp
(use-package evil-surround
  :ensure t
  :config
  (global-evil-surround-mode 1))
#+end_src
** General


The config in this section enable SPC as a prefix to a useful and commonly used
function (similar to Spacemacs/Doom/VSpaceCode).

#+begin_src emacs-lisp
(use-package general
  :ensure t
  :init
  (setq general-override-states '(insert
                                  emacs
                                  hybrid
                                  normal
                                  visual
                                  motion
                                  operator
                                  replace))
  :after evil
  :config
  (general-evil-setup t)
  (general-create-definer leader-keys
    :states '(normal visual emacs motion) ; consider adding motion for using with easymotion
    :keymaps 'override 
    :prefix "SPC")
  (general-create-definer local-leader-keys
    :states '(normal visual emacs motion) ; consider adding motion for using with easymotion
    :keymaps 'override 
    :prefix "SPC m")
  )
#+end_src

*** Eval keybindings

#+begin_src emacs-lisp
(leader-keys
  "e"     '(:ignore t       :wk "Eval")
  "e b"   '(eval-buffer     :wk "Eval elisp in buffer")
  "e d"   '(eval-defun      :wk "Eval defun")
  "e e"   '(eval-expression :wk "Eval elisp expression")
  "e l"   '(eval-last-sexp  :wk "Eval last sexression")
  "e r"   '(eval-region     :wk "Eval region"))
#+end_src

* Navigation

** Dired

#+begin_src emacs-lisp
  (use-package dired
    :after evil evil-collection general
    ;; :commands (dired dired-jump)
    ;; :bind (("C-x C-j" . dired-jump))
    :custom ((dired-listing-switches "-agho --group-directories-first"))
    :init
    (when (string= system-type "darwin")
      (setq dired-use-ls-dired t
            insert-directory-program "/usr/local/bin/gls"))
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" '(lambda () (interactive) (dired-single-buffer ".."))  ;; dired-single-up-directory still creates a new buffer for w/e reason
      "l" 'dired-single-buffer)
    (leader-keys
      "d"   '(dired      :wk "dired")
      "j d" '(dired-jump :wk "dired-jump")))

  (use-package dired-single
    :ensure t
    :after dired)

  (use-package all-the-icons-dired
    :ensure t
    :after dired
    :hook (dired-mode-hook . all-the-icons-dired-mode))

  (use-package dired-hide-dotfiles
    :ensure t
    :after dired
    :hook (dired-mode-hook . dired-hide-dotfiles-mode)
    :init
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'dired-hide-dotfiles-mode))
#+end_src

*** MacOS specific setting for Dired

OS X's ls function does not support the --group-directories-first switch. In order to enable this, install GNU core utils:

#+begin_src shell

brew install coreutils

#+end_src

** Buffer management

Add function to kill all buffers except current one.

#+begin_src emacs-lisp
(defun kill-other-buffers ()
  "Kill all other buffers."
  (interactive)
  (mapc 'kill-buffer (delq (current-buffer) (buffer-list))))
#+end_src

Keybindings for buffer management.
#+begin_src emacs-lisp
(leader-keys
  "TAB" '(consult-buffer                     :wk "Switch buffer")
  "b"   '(:ignore t                          :wk "Buffer")
  "b b" '(ibuffer                            :wk "Ibuffer")
  "b c" '(clone-indirect-buffer-other-window :wk "Clone indirect buffer other window")
  "b k" '(kill-current-buffer                :wk "Kill current buffer")
  "b n" '(next-buffer                        :wk "Next buffer")
  "b p" '(previous-buffer                    :wk "Previous buffer")
  "b B" '(ibuffer-list-buffers               :wk "Ibuffer list buffers")
  "b K" '(kill-buffer                        :wk "Kill buffer")
  "b 1" '(kill-other-buffers                 :wk "Kill other buffers"))
#+end_src

** File management

#+begin_src emacs-lisp
(leader-keys
 "f"   '(:ignore t           :wk "File")
 "."   '(find-file           :wk "Find file")
 "f f" '(find-file           :wk "Find file")
 "f F" '(consult-find        :wk "Consult find")
 "f g" '(consult-ripgrep     :wk "Consult ripgrep")
 "f r" '(consult-recent-file :wk "Recent files")
 "f s" '(save-buffer         :wk "Save file")
 "f u" '(sudo-edit-find-file :wk "Sudo find file")
 "f C" '(copy-file           :wk "Copy file")
 "f D" '(delete-file         :wk "Delete file")
 "f R" '(rename-file         :wk "Rename file")
 "f S" '(write-file          :wk "Save file as...")
 "f U" '(sudo-edit           :wk "Sudo edit file"))
#+End_src

** Avy

Package to easily navigate cursor within buffers. Using this over evil-easymotion because Avy does not distinguish between forward and backward and allows jumping across visible buffers.

#+begin_src emacs-lisp
    (use-package avy
      :ensure t
      :after consult
      :config
      (leader-keys
        "j"   '(:ignore t           :wk "Jump to")
        "j f" '(avy-goto-char       :wk "Find char")
        "j s" '(avy-goto-char-2     :wk "Find char 2")
        "j c" '(avy-goto-char-timer :wk "Find char timer")
        "j j" '(avy-goto-char-timer :wk "Find char timer")
        "j l" '(avy-goto-line       :wk "Jump to line")
        "j h" '(consult-outline     :wk "Jump to heading")))
#+end_src

** Tabs

#+begin_src emacs-lisp
(use-package tab-bar
  :ensure t
  :hook (server-after-make-frame-hook . (lambda () (tab-bar-rename-tab "main")))
  :init  
  (defun tab-bar-tab-name-format-comfortable (tab i)
    (propertize (concat " " (tab-bar-tab-name-format-default tab i) " ")
                'face (funcall tab-bar-tab-face-function tab)))
  (add-to-list 'tab-bar-format 'tab-bar-format-align-right 'append)
  (add-to-list 'tab-bar-format 'tab-bar-format-global 'append)
  (setq global-mode-string '("  " display-time-string battery-mode-line-string))
  :custom
  (tab-bar-show t)
  (tab-bar-close-button-show nil)
  (tab-bar-new-button-show nil)
  (tab-bar-tab-name-format-function #'tab-bar-tab-name-format-comfortable)
  :custom-face
  (tab-bar ((t (:background nil :inherit 'mode-line :font "IBM Plex Mono" :height 1.0 :foreground "white"))))
  (tab-bar-tab ((t (:bold t :height 1.1 :foreground "sienna"))))
  (tab-bar-tab-inactive ((t (:background nil :inherit 'mode-line :height 1.1 ))))
  :config
  (leader-keys
    "t" '(:keymap tab-prefix-map :wk "Tabs")))


;; (setq global-mode-string '(" " display-time-string battery-mode-line-string))  ; Should be set after doom-modeline because it resets this value
#+end_src

* Themes and fonts

** all-the-icons

#+begin_src emacs-lisp
(use-package all-the-icons
  :ensure t)
#+end_src

** Theme

#+begin_src emacs-lisp
(use-package doom-themes
  :ensure t
  :init
  (setq doom-themes-enable-bold t
	doom-themes-enable-italic t)
  (load-theme 'doom-vibrant t))  ;; Ones I liked and used: doom-one, doom-dark+, doom-solarized-light, doom-snazzy, doom-palenight
#+end_src

Other good themes:

- doom-palenight
- doom-one
- doom-vibrant
- doom-dark+ (VS Code like)
- doom-tomorrow-night
- doom-xcode
- doom-material
- doom-ayu-mirage
- doom-monokai-pro


** Battery formatting

This section contains my custom setup to format =battery-mode-line-string=, which will be shown at the top in the global tab-bar. It is mainly copied from the source of =smart-mode-line= and adjusted to my own liking. Main reason for doing this myself is I am not using any other functions of =smart-mode-line=, and =sml/setup=  also messes up the branch name in the mode-line (https://github.com/Malabarba/smart-mode-line/issues/255).

*** Battery functions

#+begin_src emacs-lisp
(defun duy/charging-wsl ()
  "Check whether WSL computer is charging"
  (let ((result (funcall battery-status-function)))
    (let ((charging (cdr (assoc 66 result))))
      (if (not (string= charging "Discharging")) t nil))))

(defun duy/charging-macos ()
  "Check whether MacOS computer is charging"
  (let ((result (funcall battery-status-function)))
    (let ((charging (cdr (assoc 76 result))))
      (if (string= charging "AC") t nil))))

(defun duy/charging ()
  "Check whether computer is charging"
  (if duy/is-wsl (duy/charging-wsl)
    (if duy/is-macos (duy/charging-macos) nil)))

(defun duy/battery-percentage nil
  "Get battery percentage (100% = 1000000)"
  (let
      ((result
        (funcall battery-status-function)))
    (let
        ((percentage-string
          (cdr
           (assoc 112 result))))
      (let
          ((percentage
            (string-to-number percentage-string)))
        percentage))))

(defun duy/battery-icon ()
  "Set battery icon based on battery charge status and percentage"
  (if (duy/charging) (all-the-icons-faicon "plug" :v-adjust 0.04)
    (if (> (duy/battery-percentage) 95.0) (all-the-icons-faicon "battery-full" :v-adjust 0.04)
      (if (> (duy/battery-percentage) 70.0) (all-the-icons-faicon "battery-three-quarters" :v-adjust 0.04)
        (if (> (duy/battery-percentage) 40.0) (all-the-icons-faicon "battery-half" :v-adjust 0.04)
          (if (> (duy/battery-percentage) battery-load-critical) (all-the-icons-faicon "battery-quarter" :v-adjust 0.04) (all-the-icons-faicon "battery-empty" :v-adjust 0.04)))))))

(defface duy/battery-charging
  '((t :foreground "ForestGreen" :weight normal)) "")

(defface duy/battery-discharging
  '((t :inherit warning :weight normal)) "")

(defun duy/set-battery-font ()
  "Set `duy/battery' face depending on battery state."
  (if (duy/charging)
      (copy-face 'duy/battery-charging 'duy/battery)
    (copy-face 'duy/battery-discharging 'duy/battery)))

(defadvice battery-update (before duy/set-battery-font activate)
  "Fontify the battery display."
  (duy/set-battery-font)
  (if duy/is-macos
      (setq battery-mode-line-format (concat " " (duy/battery-icon) " [%b%p%] "))
      (setq battery-mode-line-format (concat " " (duy/battery-icon) "[%b%p%] "))))

(defun duy/battery-formatting ()
  "Apply battery formatting when updating battery status"
  (eval-after-load 'battery
    '(defadvice battery-update (after duy/after-battery-update-advice () activate)
       "Change battery color and icon."
       (when battery-mode-line-string
         (setq battery-mode-line-string
               (propertize battery-mode-line-string
                           'face 'duy/battery))))))
#+end_src

*** Set battery string format

#+begin_src emacs-lisp
(duy/battery-formatting)
(display-battery-mode)
(add-hook 'server-after-make-frame-hook 'battery-update)
#+end_src

** Modeline

*** Doom modeline

Currently using mood-line as a test.

This package depends on all-the-icons package. When installing Doom modeline for the first time, please run 'all-the-icons-install-fonts' via M-x first.

#+begin_src emacs-lisp
;; (use-package doom-modeline
;;   :ensure t
;;   :config
;;   (setq doom-modeline-fn-alist (remove '(battery . doom-modeline-segment--battery) doom-modeline-fn-alist))
;;   (doom-modeline-mode 1)
;;   ;; (display-time)
;;   ;; (display-battery-mode)
;;   :custom
;;   (display-time-24hr-format t)
;;   (display-time-day-and-date t))
#+end_src

Ensure icons are used in Daemon mode:

#+begin_src emacs-lisp
;; (add-hook 'server-after-make-frame-hook
;;  (lambda ()
;;      (setq doom-modeline-icon (display-graphic-p))))
#+end_src

NOTE: ~(doom-modeline-mode)~ results in ~(error "bar is not a defined segment")~ in emacs@29. See also: https://githubhot.com/repo/seagle0128/doom-modeline/issues/505

To fix, run this code *once*:

#+begin_src emacs-lisp
;; (setq doom-modeline-fn-alist
;;       (--map
;;        (cons (remove-pos-from-symbol (car it)) (cdr it))
;;        doom-modeline-fn-alist))
#+end_src

*** Mood-line

Currently trying =mood-line= over =doom-modeline= as the latter messes up the battery string in the top right corner.

#+begin_src emacs-lisp
(use-package mood-line
  :ensure t
  :init
  ;; (setq battery-mode-line-format (concat " " (duy/battery-icon) "%b%p% ")
  (setq mode-line-misc-info (remove '(global-mode-string ("" global-mode-string)) mode-line-misc-info))
  (mood-line-mode)
  :custom
  (display-time-24hr-format t)
  (display-time-day-and-date t)
  :config
  (display-time-mode)
  (display-battery-mode))
#+end_src

** Fonts

The used fonts have different names on different computers:

#+begin_src emacs-lisp
(if (string= system-name "Duys-MBP.home")
    (setq duy/default-font "FiraMono Nerd Font Mono"
          duy/variable-font "IBM Plex Sans"
          duy/default-font-size 12.0
          duy/variable-font-size 12.0)
  (if (string= system-name "NL5CG1462QH6")
      (setq duy/default-font "FiraMono Nerd Font Mono"
            duy/variable-font "IBM Plex Sans"
            duy/default-font-size 10.5
            duy/variable-font-size 12.0)
    (setq duy/default-font nil
          duy/variable-font nil
          duy/default-font-size nil
          duy/variable-font-size nil)))
#+end_src

Set fonts:

#+begin_src emacs-lisp
  (set-face-attribute 'default nil :font (font-spec :family duy/default-font))
  (set-face-attribute 'fixed-pitch nil :font (font-spec :family duy/default-font))
  (set-face-attribute 'variable-pitch nil :font (font-spec :family duy/variable-font))
#+end_src

** Font settings for daemon mode

Font settings for daemon mode:

#+begin_src emacs-lisp
(defun duy/setup-font-faces-daemon()
  (when (daemonp)
    (set-face-attribute 'default nil :font (font-spec :family duy/default-font :size duy/default-font-size))
    (set-face-attribute 'fixed-pitch nil :font (font-spec :family duy/default-font :size duy/default-font-size))
    (set-face-attribute 'variable-pitch nil :font (font-spec :family duy/variable-font :size duy/variable-font-size))))

  (add-hook 'after-init-hook 'duy/setup-font-faces-daemon)
  (add-hook 'server-after-make-frame-hook 'duy/setup-font-faces-daemon)
#+end_src

* Terminals

** Function to disable exit confirmation query for shells and terminals

#+begin_src emacs-lisp
(defun set-no-process-query-on-exit ()
  (let ((proc (get-buffer-process (current-buffer))))
    (when (processp proc)
      (set-process-query-on-exit-flag proc nil))))
#+end_src

** vterm

#+begin_src emacs-lisp
  (use-package vterm
    :ensure t
    :bind (:map vterm-mode-map
                ("C-b" . vterm-send-C-b))
    :config
    (dolist (mode '(term-mode-hook
                    shell-mode-hook
                    vterm-mode-hook
                    eshell-mode-hook))
      (add-hook mode (lambda () (display-line-numbers-mode 0)))
      (add-hook mode (lambda () (setq-local global-hl-line-mode nil)))
      (add-hook mode 'set-no-process-query-on-exit)))
#+end_src

I also enabled directory tracking and named vterm buffer, see also here how to setup: https://github.com/akermu/emacs-libvterm

** vterm-toggle

#+begin_src emacs-lisp
(use-package vterm-toggle
  :ensure t
  :custom
  (vterm-buffer-name-string "vterm: %s")
  (vterm-toggle-project-root t)
  (vterm-toggle-scope 'project)
  :config
  (setq vterm-toggle-fullscreen-p nil)
  (add-to-list 'display-buffer-alist
               '((lambda (buffer-or-name _)
                   (let ((buffer (get-buffer buffer-or-name)))
                     (with-current-buffer buffer
                       (or (equal major-mode 'vterm-mode)
                           (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                 (display-buffer-reuse-window display-buffer-at-bottom)
                 (display-buffer-reuse-window display-buffer-in-direction)
                 ;;display-buffer-in-direction/direction/dedicated is added in emacs27
                 ;;(direction . bottom)
                 (dedicated . t) ;dedicated is supported in emacs27
                 (reusable-frames . visible)
                 (window-height . 0.3)))
  (leader-keys
    "'" '(vterm-toggle :wk "vterm"))
  (bind-keys  ; For some reason :bind interferes with the SPC ' binding here
   :map vterm-mode-map
   ("C-<return>" . vterm-toggle-insert-cd)))
#+end_src

** exec-path-from-shell

#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :ensure t
  :if duy/is-macos
  :defer nil
  :config
  (exec-path-from-shell-copy-env "PATH")
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize))
  (when (daemonp)
    (exec-path-from-shell-initialize)))
#+end_src

* Completion and navigation
** Vertico

#+begin_src emacs-lisp
(use-package vertico
  :ensure t
  :bind (:map vertico-map
              ("C-j" . vertico-next)
              ("C-k" . vertico-previous)
              ("C-f" . vertico-exit)
              :map minibuffer-local-map
              ("M-h" . backward-kill-word))
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode))
#+end_src

*** Vertico-directory

#+begin_src emacs-lisp
(use-package vertico-directory
  :after vertico
  :ensure nil
  ;; More convenient directory navigation commands
  :bind (:map vertico-map
              ("RET" . vertico-directory-enter)
              ("DEL" . vertico-directory-delete-char)
              ("C-<backspace>" . vertico-directory-delete-word)))
#+end_src

** Orderless

#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(partial-completion orderless flex))
  (completion-category-defaults nil)
  (read-file-name-completion-ignore-case t)
  (completion-category-overrides '((file (styles partial-completion))
                                   (minibuffer (initials orderless)))))
#+end_src

** Savehist

#+begin_src emacs-lisp
;; Persist history over Emacs restarts. Vertico sorts by history position.
(use-package savehist
  :ensure t
  :defer 2
  :config
  (savehist-mode))
#+end_src

** Marginalia

#+begin_src emacs-lisp
(use-package marginalia
  :pin melpa
  :ensure t
  :defer 3
  :custom (marginalia-annotators '(marginalia-annotators-light))
  :config
  (marginalia-mode))
#+end_src

** Which-key

#+begin_src emacs-lisp
(use-package which-key
  :ensure t
  :defer 4
  :diminish which-key-mode
  :custom
  (which-key-compute-remaps t)
  :config
  (which-key-mode 1))
#+end_src

** Company

#+begin_src emacs-lisp
;; (use-package company
;;   :ensure t
;;   :defer t
;;   :diminish ""
;;   :custom
;;   (company-dabbrev-other-buffers t)
;;   (company-dabbrev-code-other-buffers t)
;;   ;; M-<num> to select an option according to its number.
;;   (company-show-numbers t)
;;   ;; Only 2 letters required for completion to activate.
;;   (company-minimum-prefix-length 3)
;;   ;; Do not downcase completions by default.
;;   (company-dabbrev-downcase nil)
;;   ;; Even if I write something with the wrong case,
;;   ;; provide the correct casing.
;;   (company-dabbrev-ignore-case t)
;;   ;; company completion wait
;;   (company-idle-delay 0.2)
;;   ;; No company-mode in shell & eshell
;;   (company-global-modes '(not eshell-mode shell-mode))
;;   :hook ((prog-mode-hook . company-mode)))
#+end_src

** Corfu

Alternative to company.

#+begin_src emacs-lisp
(use-package corfu
  :ensure t
  :bind (:map corfu-map
         ("C-j" . corfu-next)
         ("C-k" . corfu-previous)
         ("TAB" . corfu-insert)
         ("RET" . nil)
         :map org-mode-map
         ("C-," . nil))
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  :init
  (global-corfu-mode)
  (global-set-key (kbd "M-i") #'completion-at-point))
#+end_src

Enabling icons in Corfu:

#+begin_src emacs-lisp
(use-package kind-icon
  :ensure t
  :after corfu
  :custom
  (kind-icon-default-face 'corfu-default) ; to compute blended backgrounds correctly
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
#+end_src

** Consult

#+begin_src emacs-lisp
(use-package consult
  :ensure t
  :bind (("C-s" . consult-line)
         :map minibuffer-local-map
         ("C-r" . consult-history)))
#+end_src

** Embark

#+begin_src emacs-lisp
  (use-package embark
    :ensure t
    :bind
    (("C-;" . embark-act)          ;; pick some comfortable binding
     ("C-:" . embark-dwim)         ;; good alternative: M-.
     ("C-h B" . embark-bindings))
    :config
    (when (and (eq system-type 'gnu/linux)
	       (string-match "WSL" operating-system-release))
      (bind-keys
       :map embark-url-map
       ("e" . browse-url-edge)
       :map embark-file-map
       ("<C-return>" . duy/open-file-with-wsl))))
  ;; :map minibuffer-local-map
  ;; (("C-." . embark-act)))) ;; alternative for `describe-bindings'

  (use-package embark-consult
    :ensure t
    :after (embark consult)
    :demand t ; only necessary if you have the hook below
    ;; if you want to have consult previews as you move around an
    ;; auto-updating embark collect buffer
    :hook
    (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

*** WSL/Windows specific Embark actions

#+begin_src emacs-lisp
;; (when (and (eq system-type 'gnu/linux)
;;            (string-match "WSL" operating-system-release))
;; (bind-keys
;;    :map embark-url-map
;;    ("e" . browse-url-edge)
;;    :map embark-file-map
;;    ("<C-return>" . duy/open-file-with-wsl)))
#+end_src

* Windows and movement

** ace-window

#+begin_src emacs-lisp
(use-package ace-window
  :ensure t
  :config
    (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)
          aw-dispatch-always t)
    (leader-keys
      "w" '(ace-window :wk "ace-window")))
#+end_src
  
* Popper

#+begin_src emacs-lisp
(use-package popper
  :ensure t
  :bind (("C-`"   . popper-toggle-latest)
         ("M-`"   . popper-cycle)
         ("C-M-`" . popper-toggle-type)
         ("M-'"   . popper-kill-latest-popup))
  :init
  (setq popper-reference-buffers
        '("\\*Messages\\*"
	    "\\*Warnings\\*"
          "Output\\*$"
          "\\*Async Shell Command\\*"
          help-mode
          helpful-mode
	    "\\*eldoc\\*"
	    "\\*PDF-Occur\\*"
          compilation-mode))
  (popper-mode +1)
  (popper-echo-mode +1))
#+end_src

* Spell / syntax checking

#+begin_src emacs-lisp
(defun duy/flyspell-delete-all-overlays ()
  "Delete all flyspell checks in buffer."
  (interactive)
  (flyspell-delete-all-overlays))
#+end_src

#+begin_src emacs-lisp
(use-package flyspell
  :defer t
  :config
  (leader-keys
    ;; Use evil-next/prev-flyspell-error to navigate
    "s"   '(nil                              :wk "Spell check")
    "s r" '(flyspell-region                  :wk "Flyspell region")
    "s b" '(flyspell-buffer                  :wk "Flyspell buffer")
    "s B" '(duy/flyspell-delete-all-overlays :wk "Delete spell check buffer")))
#+end_src

#+begin_src emacs-lisp
(use-package flyspell-correct
  :ensure t
  :after flyspell
  :bind ([remap ispell-word] . flyspell-correct-wrapper))
#+end_src

* Version control

#+begin_src emacs-lisp
(use-package magit
  :ensure t
  :config
  (leader-keys
    "g"   '(:ignore t                 :wk "Git")
    "g s" '(magit                     :wk "Magit status")
    "g m" '(activate-smerge-mode/body :wk "Smerge")))
#+end_src

#+begin_src emacs-lisp
(defhydra activate-smerge-mode ()
  "Smerge mode"
  ("j" smerge-next "next")
  ("k" smerge-prev "prev")
  ("u" smerge-keep-upper "keep upper")
  ("l" smerge-keep-lower "keep lower")
  ("c" smerge-keep-current "keep current")
  ("h" smerge-refine "highlight")
  ("d" smerge-kill-current "delete current")
  ("a" smerge-keep-all "keep all")
  ("b" smerge-keep-base "keep base")
  ("q" nil "quit"))
#+end_src

* Org mode

** Basic setup

#+begin_src emacs-lisp
(defun duy/org-mode-setup ()
  (variable-pitch-mode 1)
  (visual-line-mode 1)
  (evil-org-mode 1)
  (display-line-numbers-mode 0)
  (setq flyspell-generic-check-word-predicate 'org-mode-flyspell-verify)  ;; Don't spell check src blocks
  (setq-local corfu-auto nil))  ;; Don't auto complete in org-buffers (to avoid org-roam link inserts)
#+end_src

#+begin_src emacs-lisp
(use-package org
  :ensure t
  :custom
  (org-babel-load-languages            ; Languages allowed to run in Org Src blocks
   '((emacs-lisp . t)
     (python . t)
     (jupyter . t)))
  (org-confirm-babel-evaluate nil)     ; Do not ask for confirmation when evaluating src blocks
  (org-catch-invisible-edits 'show)    ; When making invisible edits, show the location of the edit
  (org-ellipsis " ▼ ")
  (org-src-fontify-natively t)         ; Fontify code in src blocks
  (org-edit-src-content-indentation 2) ; Indentation within the src blocks
  (org-startup-indented t)             ; Org headings are indented, as is the text within the headings
  (org-hide-leading-stars nil)
  (org-src-preserve-indentation t)
  (org-hide-emphasis-markers t)        ; Hide markers around emphasised word (e.g. *bold*, /italic/ etc.)
  (org-adapt-indentation t)
  (org-structure-template-alist '(("a" . "export ascii")
                                  ("c" . "center")
                                  ("C" . "comment")
                                  ("e" . "example")
                                  ("E" . "export")
                                  ("l" . "export latex")
                                  ("py" . "src python")
                                  ("sh" . "src h")
                                  ("q" . "quote")
                                  ("s" . "src")
                                  ("v" . "verse")
                                  ("el" . "src emacs-lisp")
                                  ("d" . "definition")
                                  ("t" . "theorem")))
  :custom-face
  ;; (variable-pitch ((t (:family "IBM Plex Sans"))))
  (org-document-title ((t (:weight bold :height 1.5))))
  (org-done ((t (:strike-through t :weight bold))))
  (org-headline-done ((t (:strike-through t))))
  (org-level-1 ((t (:height 1.3 :weight bold))))
  (org-level-2 ((t (:height 1.2 :weight bold))))
  (org-level-3 ((t (:height 1.1 :weight bold))))
  (org-image-actual-width (/ (display-pixel-width) 2))
  (org-block ((nil (:foreground nil :inherit 'fixed-pitch))))
  (org-table ((nil (:inherit 'fixed-pitch))))
  (org-formula ((nil (:inherit 'fixed-pitch))))
  (org-code ((nil (:inherit (shadow fixed-pitch)))))
  (org-indent ((nil (:inherit (org-hide fixed-pitch)))))
  (org-verbatim ((nil (:inherit (shadow fixed-pitch)))))
  (org-special-keyword ((nil (:inherit (font-lock-comment-face fixed-pitch)))))
  (org-meta-line ((nil (:inherit (font-lock-comment-face fixed-pitch)))))
  (org-checkbox ((nil (:inherit 'fixed-pitch))))
  (org-block-begin-line ((nil (:inherit 'fixed-pitch))))
  :init
  (with-eval-after-load 'flycheck
    (flycheck-add-mode 'proselint 'org-mode))
  ;; Change bullets to actual bullets
  (font-lock-add-keywords 'org-mode
                          '(("^ *\\([-]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
  :hook
  (org-mode-hook . duy/org-mode-setup)
  ;; Prepend org-mode-line-string to global-mode-string when clocking in
  (org-clock-in-hook . (lambda ()
                         (delq 'org-mode-line-string global-mode-string)  ; Delete first as org-clock-in appends it automatically
                         (setq global-mode-string (add-to-list 'global-mode-string 'org-mode-line-string))
                         (setq global-mode-string (add-to-list 'global-mode-string " "))))  ;; global-mode-string should always start with an empty space
  ;; Remove the empty space added during clock in when clocking out
  ((org-clock-out-hook org-clock-cancel-hook). (lambda ()
                          (setq global-mode-string (delete " " global-mode-string))))
  :bind
  (:map org-mode-map
        ("C-M-h" . org-shiftleft)
        ("C-M-l" . org-shiftright))
  :config
  (advice-add 'org-refile :after (lambda (&rest _) (org-save-all-org-buffers)))
  (require 'org-habit)
  (require 'org-tempo)
  (leader-keys
    "o"   '(:ignore t   :wk "Org")
    "a"   '(org-agenda  :wk "Agenda")
    "c"   '(org-capture :wk "Capture")
    "C"   '(org-capture :wk "Capture"))
  (local-leader-keys
    :keymaps 'org-mode-map
    "o" '(org-open-at-point :wk "Open link")))
#+end_src

** Capture templates

#+begin_src emacs-lisp
(if (string= system-name "Duys-MBP.home")
    (setq inbox-file "~/org-roam-notes/20220101143145-inbox.org"
          general-task-file "~/org-roam-notes/20220101143545-tasks.org")
  (if (string= system-name "NL5CG1462QH6")
      (setq inbox-file "~/org-roam-notes/20220522180401-inbox.org"
            general-task-file "~/org-roam-notes/20220522181915-general_tasks.org")
    (setq inbox-file nil)))

(setq org-capture-templates
      '(("i" "Inbox" plain (file inbox-file)
         "* TODO %?\n%U\n" :clock-in nil :clock-resume t)
        ("t" "Today" plain (file general-task-file)
         "* TODO %?\n SCHEDULED: %t\n%U\n" :clock-in nil :clock-resume t)
        ))
#+end_src

** Org bullet

#+begin_src emacs-lisp
  (use-package org-bullets
    :ensure t)

  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

** Org appear

Org-appear shows the emphasis markers when your cursor is on the text, even if ~org-hide-emphasis-markers~ is set.

#+begin_src emacs-lisp
(use-package org-appear
  :ensure t
  :hook (org-mode-hook . org-appear-mode))
#+end_src

** Org roam

#+begin_src emacs-lisp
  (use-package org-roam
    :ensure t
    :init
    (setq org-roam-v2-ack t)
    :custom
    (org-roam-directory "~/org-roam-notes")
    (org-roam-completion-everywhere t)
    (org-roam-capture-templates
     '(("d" "default" plain
        "%?"
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+date: %U\n")
        :unnarrowed t)))
    (org-roam-dailies-capture-templates
     '(("d" "default" entry "* %<%I:%M %p>: %?"
        :if-new (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))))
    :bind (:map org-mode-map
                ("C-M-i" . completion-at-point)
                :map org-roam-dailies-map
                ("Y" . org-roam-dailies-capture-yesterday)
                ("T" . org-roam-dailies-capture-tomorrow))
    :config
    (require 'org-roam-dailies) ;; Ensure the keymap is available
    (setq org-roam-node-display-template #("${title:*} ${tags:40}" 11 21
                                           (face org-tag)))
    (org-roam-db-autosync-mode)
    (leader-keys
      "n"   '(:ignore t              :wk "Roam")
      "n l" '(org-roam-buffer-toggle :wk "Buffer toggle")
      "n f" '(org-roam-node-find     :wk "Find")
      "n i" '(org-roam-node-insert   :wk "Insert")
      "n t" '(org-roam-tag-add       :wk "Add tag")
      "n T" '(org-roam-tag-remove    :wk "Remove tag")
      "n d" '(org-roam-dailies-map   :wk "Dailies")))
#+end_src

* Org agenda (using org-roam)

** Helper functions

This setup primarily follows the setup from d12frosted's [[https://d12frosted.io/posts/2020-06-23-task-management-with-roam-vol1.html][blog]].

*** Vulpea

Vulpea is a package written by d12frosted with additional functions for org and org-roam. See also [[https://github.com/d12frosted/vulpea][here]].

#+begin_src emacs-lisp
(use-package vulpea
  :ensure t)
#+end_src

*** s.el

s.el is an emacs string manipulation package.

#+begin_src emacs-lisp
(use-package s
  :ensure t)
#+end_src

*** Dynamic org-agenda

- Update nodes with "project" tag if it has a TODO item.
- Set agenda files to nodes which have a "project" tag.

#+begin_src emacs-lisp
(defun vulpea-project-p ()
  "Return non-nil if current buffer has any todo entry.

TODO entries marked as done are ignored, meaning the this
function returns nil if current buffer contains only completed
tasks."
  (seq-find                                 ; (3)
   (lambda (type)
     (eq type 'todo))
   (org-element-map                         ; (2)
       (org-element-parse-buffer 'headline) ; (1)
       'headline
     (lambda (h)
       (org-element-property :todo-type h)))))

(defun vulpea-project-update-tag ()
  "Update PROJECT tag in the current buffer."
  (when (and (not (active-minibuffer-window))
             (vulpea-buffer-p))
    (save-excursion
      (goto-char (point-min))
      (let* ((tags (vulpea-buffer-tags-get))
             (original-tags tags))
        (if (vulpea-project-p)
            (setq tags (cons "project" tags))
          (setq tags (remove "project" tags)))

        ;; cleanup duplicates
        (setq tags (seq-uniq tags))

        ;; update tags if changed
        (when (or (seq-difference tags original-tags)
                  (seq-difference original-tags tags))
          (apply #'vulpea-buffer-tags-set tags))))))

(defun vulpea-buffer-p ()
  "Return non-nil if the currently visited buffer is a note."
  (and buffer-file-name
       (string-prefix-p
        (expand-file-name (file-name-as-directory org-roam-directory))
        (file-name-directory buffer-file-name))))

(defun vulpea-project-files ()
  "Return a list of note files containing 'project' tag." ;
  (seq-uniq
   (seq-map
    #'car
    (org-roam-db-query
     [:select [nodes:file]
              :from tags
              :left-join nodes
              :on (= tags:node-id nodes:id)
              :where (like tag (quote "%\"project\"%"))]))))

(defun vulpea-agenda-files-update (&rest _)
  "Update the value of `org-agenda-files'."
  (setq org-agenda-files (vulpea-project-files)))

(add-hook 'find-file-hook #'vulpea-project-update-tag)
(add-hook 'before-save-hook #'vulpea-project-update-tag)

(advice-add 'org-agenda :before #'vulpea-agenda-files-update)
#+end_src

** Org agenda settings

*** Fix title org-roam file in todo list

#+begin_src emacs-lisp
(setq org-agenda-prefix-format
      '((agenda . " %i %(vulpea-agenda-category 12)%?-12t% s")
        (todo . " %i %(vulpea-agenda-category 12) ")
        (tags . " %i %(vulpea-agenda-category 12) ")
        (search . " %i %(vulpea-agenda-category 12) ")))

(defun vulpea-agenda-category (&optional len)
  "Get category of item at point for agenda.

Category is defined by one of the following items:

- CATEGORY property
- TITLE keyword
- TITLE property
- filename without directory and extension

When LEN is a number, resulting string is padded right with
spaces and then truncated with ... on the right if result is
longer than LEN.

Usage example:

  (setq org-agenda-prefix-format
        '((agenda . \" %(vulpea-agenda-category) %?-12t %12s\")))

Refer to `org-agenda-prefix-format' for more information."
  (let* ((file-name (when buffer-file-name
                      (file-name-sans-extension
                       (file-name-nondirectory buffer-file-name))))
         (title (vulpea-buffer-prop-get "title"))
         (category (org-get-category))
         (result
          (or (if (and
                   title
                   (string-equal category file-name))
                  title
                category)
              "")))
    (if (numberp len)
        (s-truncate len (s-pad-right len " " result))
      result)))
#+end_src

*** org-super-agenda

Use org-super-agenda to group TODOs in agenda view.

#+begin_src emacs-lisp

(use-package org-super-agenda
  :ensure t
  :config
  (add-hook 'org-agenda-mode-hook 'org-super-agenda-mode)
  (setq org-super-agenda-header-map (make-sparse-keymap)))

#+end_src

*** TODOs, tags etc.

Set todo keywords, tags etc.

#+begin_src emacs-lisp

(setq org-todo-keywords
      '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d)")
        (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c)")))

(setq org-log-done 'time
      org-log-into-drawer t
      org-log-state-notes-insert-after-drawers nil)

(setq org-tag-alist (quote (("@reading" . ?r)
                            ("@coding" . ?c)
                            ("@writing" . ?w)
                            ("@office" . ?o)
                            ("@home" . ?h)
                            (:newline)
                            ("WAITING" . ?W)
                            ("HOLD" . ?H))))

(setq org-fast-tag-selection-single-key nil)
#+end_src

*** Archiving

Function to archive all done task in current org agenda/file.

#+begin_src emacs-lisp
(defun duy/org-archive-done-tasks-agenda ()
  (interactive)
  (org-map-entries
   (lambda ()
     (org-archive-subtree)
     (setq org-map-continue-from (org-element-property :begin (org-element-at-point))))
   "/DONE" 'agenda))

(defun duy/org-archive-done-tasks-file ()
  (interactive)
  (org-map-entries
   (lambda ()
     (org-archive-subtree)
     (setq org-map-continue-from (org-element-property :begin (org-element-at-point))))
   "/DONE" 'file))
#+end_src

*** Group TODOs by title

Function to automatically group TODOs by title.
#+begin_src emacs-lisp

(org-super-agenda--def-auto-group title "title of org file"
  :key-form (org-super-agenda--when-with-marker-buffer (org-super-agenda--get-marker item)
              (org-roam-db--file-title))
  :header-form key)

#+end_src

*** Layout of agenda

#+begin_src emacs-lisp
(setq duy/agenda-group-main
      '(
	(:discard (:scheduled today))
	(:discard (:scheduled past))
	(:name "Next"
	       :todo "NEXT")
	(:name "Focus"
	       :tag "focus")
	(:name "Scheduled"
	       :scheduled future)
	(:name "Waiting"
	       :todo "WAITING")
	(:discard (:anything t))
	))

(setq duy/agenda-group-today
      '(
	(:name "Today"
	       :time-grid t
	       :date today
	       :scheduled today)
	(:name "Upcoming deadlines"
               :deadline future)
	))

(setq duy/agenda-group-backlog
      '(
	(:discard (:tag "refile"))
	(:auto-title t) ;; defined with org-super-agenda--def-auto-group
	))

(setq duy/agenda-group-backlog-unscheduled
      '(
	(:discard (:tag "refile"))
	(:discard (:scheduled t))
	(:discard (:deadline today))
	(:auto-title t) ;; defined with org-super-agenda--def-auto-group
	))

(setq duy/agenda-group-inbox
      '(
	(:name ""
	       :tag "refile")
	(:discard (:anything t))
	))

(setq org-agenda-custom-commands
      `((" " "Agenda"
	 ((agenda "" ((org-agenda-span 'day)
		      (org-super-agenda-groups duy/agenda-group-today)))
	  (todo "" ((org-agenda-overriding-header "Tasks")
		    (org-super-agenda-groups duy/agenda-group-main)))
	  (todo "" ((org-agenda-overriding-header "Inbox")
		    (org-super-agenda-groups duy/agenda-group-inbox)))
	  (todo "TODO" ((org-agenda-overriding-header "Backlog")
			(org-super-agenda-groups duy/agenda-group-backlog-unscheduled)))
	  ))
	("b" "Backlog"
	 ((todo "TODO" ((org-agenda-overriding-header "Backlog")
			(org-super-agenda-groups duy/agenda-group-backlog))))
	 )))
#+end_src

*** org-agenda tags display settings

Align all tags at the right border of the agenda window:

#+begin_src emacs-lisp
  (defun duy/realign-agenda-tags ()
    "Put the agenda tags at the right border of the agenda window."
    (setq org-agenda-tags-column (- 5 (window-width)))
    (org-agenda-align-tags))

  (add-hook 'org-agenda-finalize-hook 'duy/realign-agenda-tags)
#+end_src

Hide the =project= tag in org-agenda, since by definition in our setup all items will have the tag:

#+begin_src emacs-lisp
(setq org-agenda-hide-tags-regexp (regexp-opt '("project")))
#+end_src

** Inbox management
 
*** Function to process inbox item

#+begin_src emacs-lisp
(defun duy/org-agenda-process-inbox-item ()
  "Process a single item in the org-agenda."
  (interactive)
  (org-with-wide-buffer
   (org-agenda-set-tags)
   ;; (org-agenda-priority)
   (org-agenda-refile nil nil t)))
#+end_src

*** Functions to process inbox

#+begin_src emacs-lisp
(defun duy/bulk-process-entries ()
  (if (not (null org-agenda-bulk-marked-entries))
      (let ((entries (reverse org-agenda-bulk-marked-entries))
            (processed 0)
            (skipped 0))
        (dolist (e entries)
          (let ((pos (text-property-any (point-min) (point-max) 'org-hd-marker e)))
            (if (not pos)
                (progn (message "Skipping removed entry at %s" e)
                       (cl-incf skipped))
              (goto-char pos)
              (let (org-loop-over-headlines-in-active-region) (funcall 'duy/org-agenda-process-inbox-item))
              ;; `post-command-hook' is not run yet.  We make sure any
              ;; pending log note is processed.
              (when (or (memq 'org-add-log-note (default-value 'post-command-hook))
                        (memq 'org-add-log-note post-command-hook))
                (org-add-log-note))
              (cl-incf processed))))
        (org-agenda-redo)
        (unless org-agenda-persistent-marks (org-agenda-bulk-unmark-all))
        (message "Acted on %d entries%s%s"
                 processed
                 (if (= skipped 0)
                     ""
                   (format ", skipped %d (disappeared before their turn)"
                           skipped))
                 (if (not org-agenda-persistent-marks) "" " (kept marked)")))))

(defun duy/org-process-inbox ()
  "Called in org-agenda-mode, processes all inbox items."
  (interactive)
  (org-agenda-bulk-mark-regexp "refile:")
  (duy/bulk-process-entries))
#+end_src

*** Org refile settings

Refile targets are set to all files in the org-roam-notes folder.

#+begin_src emacs-lisp
(setq myroamfiles (directory-files org-roam-directory t "org$"))

;; -------- refile settings -----
(setq org-refile-targets '((org-agenda-files :maxlevel . 5) (myroamfiles :maxlevel . 5)))
(setq org-refile-use-outline-path 'file)  ;; 'file or nil
(setq org-outline-path-complete-in-steps nil)
(setq org-refile-allow-creating-parent-nodes 'confirm)
#+end_src

#+begin_src emacs-lisp
(defun vulpea-roam-files-update (&rest _)
  "Update the value of `myroamfiles'."
  (setq myroamfiles (directory-files org-roam-directory t "org$")))

(advice-add 'org-agenda :before #'vulpea-roam-files-update)
#+end_src

Some ideas for the future:

- Project nodes have "project" tags, which are added by myself.
- Nodes have "task" tags based on existence of TODO items.
- Org agenda items are nodes with a "task" tag.
- Refile targets are nodes with a "project" or "task" tag.
  
** Archiving

Function to archive all done task in current org agenda/file.

#+begin_src emacs-lisp
(defun duy/org-archive-done-tasks-agenda ()
  (interactive)
  (org-map-entries
   (lambda ()
     (org-archive-subtree)
     (setq org-map-continue-from (org-element-property :begin (org-element-at-point))))
   "/DONE" 'agenda))

(defun duy/org-archive-done-tasks-file ()
  (interactive)
  (org-map-entries
   (lambda ()
     (org-archive-subtree)
     (setq org-map-continue-from (org-element-property :begin (org-element-at-point))))
   "/DONE" 'file))
#+end_src

** Update org-agenda keybindings

*** General agenda bindings

#+begin_src emacs-lisp
(general-define-key
 :states '(normal motion override)
 :keymaps '(org-agenda-mode-map)
 "r"   '(:ignore t                         :wk "Refile")
 "r r" '(duy/org-agenda-process-inbox-item :wk "Refile item")
 "r i" '(duy/org-process-inbox             :wk "Process inbox")
 "d a" '(duy/org-archive-done-tasks-agenda :wk "Archive all done tasks"))
#+end_src

*** org-calendar bindings

#+begin_src emacs-lisp

(defmacro my-org-in-calendar (command)
  (let ((name (intern (format "my-org-in-calendar-%s" command))))
    `(progn
       (defun ,name ()
         (interactive)
         (org-eval-in-calendar '(call-interactively #',command)))
       #',name)))

(general-def org-read-date-minibuffer-local-map
  "h" (my-org-in-calendar calendar-backward-day)
  "l" (my-org-in-calendar calendar-forward-day)
  "k" (my-org-in-calendar calendar-backward-week)
  "j" (my-org-in-calendar calendar-forward-week)
  "C-h" (my-org-in-calendar calendar-backward-month)
  "C-l" (my-org-in-calendar calendar-forward-month)
  "C-k" (my-org-in-calendar calendar-backward-year)
  "C-j" (my-org-in-calendar calendar-forward-year))
#+end_src

* Writing

** Thesaurus

#+begin_src emacs-lisp
  (use-package powerthesaurus
    :ensure t
    :config
    (leader-keys
      "s d" '(powerthesaurus-lookup-dwim :wk "Powerthesaurus")))
#+end_src

** Olivetti

#+begin_src emacs-lisp
  (use-package olivetti
    :ensure t
    :defer t
    :diminish
    :custom
    (olivetti-body-width 0.67)
    (olivetti-minimum-body-width 80)
    (olivetti-recall-visual-line-mode-entry-state t)
    (olivetti-style "fancy")
    :custom-face
    (olivetti-fringe ((t (:background "#122")))))
#+end_src

* Web browsing

Open URLs in qutebrowser:

#+begin_src emacs-lisp
  (setq browse-url-browser-function 'browse-url-generic
        browse-url-generic-program "qutebrowser")
#+end_src

Keybindings for web-browsing:

#+begin_src emacs-lisp
  (leader-keys
    "u" '(browse-url :wk "Browse URL"))
#+end_src

* Pandoc

* Programming

** Project management

#+begin_src emacs-lisp
(use-package project
  :ensure t
  :init
  (setq project-switch-commands '((project-find-file "Find file" "f")
                                  (project-find-dir "Find dir" "d")
                                  (project-dired "Dired" "D")
                                  (consult-ripgrep "ripgrep" "g")
                                  (magit-status "Magit" "m")))
  :config
  (leader-keys
    "p"   '(nil                    :wk "Project")
    "p p" '(project-switch-project :wk "Switch project")
    "p f" '(project-find-file      :wk "Find file")
    "p d" '(project-find-dir       :wk "Find dir")
    "p D" '(project-dired          :wk "Dired project root")
    "p k" '(project-kill-buffers   :wk "Kill project buffers")
    "p b" '(consult-project-buffer :wk "Switch buffer")
    "p g" '(consult-ripgrep        :wk "Consult ripgrep")))
#+end_src

*** Start vterm in project root

Current the function below is unused as we are using ~vterm-toggle~ with ~vterm-toggle-project-root~ and ~vterm-toggle-scope~.

#+begin_src emacs-lisp
;; (defun duy/project-vterm ()
;;   "Start an inferior shell in the current project's root directory.
;; If a buffer already exists for running a shell in the project's root,
;; switch to it.  Otherwise, create a new shell buffer.
;; With \\[universal-argument] prefix arg, create a new inferior shell buffer even
;; if one already exists."
;;   (interactive)
;;   (require 'comint)
;;   (let* ((default-directory (project-root (project-current t)))
;;          (default-project-shell-name (project-prefixed-buffer-name "vterm"))
;;          (shell-buffer (get-buffer default-project-shell-name)))
;;     (if (and shell-buffer (not current-prefix-arg))
;;         (if (comint-check-proc shell-buffer)
;;             (pop-to-buffer shell-buffer (bound-and-true-p display-comint-buffer-action))
;;           (vterm shell-buffer))
;;       (vterm (generate-new-buffer-name default-project-shell-name)))))
#+end_src

** direnv and envrc for setting local virtual environment variables

Ensure =direnv= is installed via your OS package manager.

#+begin_src emacs-lisp
(use-package envrc
  :ensure t
  :init
  (envrc-global-mode 1))
#+end_src

** LSP

#+begin_src emacs-lisp
(use-package eglot
  :ensure t
  :defer t
  :hook (python-mode-hook . eglot-ensure)
  :init
  (define-key evil-normal-state-map (kbd "M-.") nil)
  (define-key evil-normal-state-map (kbd "C->") 'evil-repeat-pop-next)
  :config
  (leader-keys
    "l"     '(nil                              :wk "Lsp")
    "l e"   '(nil                              :wk "Errors")
    "l e n" '(flymake-goto-next-error          :wk "Next error")
    "l e p" '(flymake-goto-prev-error          :wk "Previous error")
    "l e d" '(flymake-show-buffer-diagnostics  :wk "Buffer diagnostics")
    "l e D" '(flymake-show-project-diagnostics :wk "Project diagnostics")
    "l d"   '(xref-find-definitions            :wk "Find definition")
    "l r"   '(xref-find-references             :wk "Find references")))
#+end_src

** Python

#+begin_src emacs-lisp
(use-package python
  :ensure t
  :custom
  (python-indent-guess-indent-offset-verbose nil))
#+end_src

*** Poetry

Using poetry to manage python environments for coding projects. This is important for ~eglot~ to use the correct environment for linting.

Alternatives include [[https://github.com/jorgenschaefer/pyvenv][pyvenv.el]], [[https://github.com/pythonic-emacs/pyenv-mode][pyenv-mode.el]], [[https://github.com/necaris/conda.el][conda.el]] and [[https://github.com/pythonic-emacs/anaconda-mode][anaconda-mode.el]]. pyenv-mode can be used in conjunction with projectile, see also [[https://www.reddit.com/r/emacs/comments/tenq8z/help_using_lspmodeeglot_for_python_and_virtualenvs/][here]].

#+begin_src emacs-lisp
(use-package poetry
  :ensure t
  :defer t)
  ;; :config
  ;; ;; Checks for the correct virtualenv. Better strategy IMO because the default
  ;; ;; one is quite slow.
  ;; ;; (setq poetry-tracking-strategy 'switch-buffer)
  ;; (setq poetry-tracking-strategy 'post-command)
  ;; :hook (python-mode-hook . poetry-tracking-mode))
#+end_src

# Note: ~poetry-tracking-strategy 'switch-buffer~ makes poetry check venv even when previewing buffers, so changed it back to the default setting now.

Currently using in combination with =direnv= ([[https://github.com/direnv/direnv/wiki/Python][setup instructions]]).

*** Blacken

#+begin_src emacs-lisp
(use-package blacken
  :ensure t
  :defer t
  :custom
  (blacken-allow-py36 t)
  (blacken-skip-string-normalization t)
  :hook (python-mode-hook . blacken-mode))
#+end_src

*** Numpydoc

#+begin_src emacs-lisp
(use-package numpydoc
  :ensure t
  :defer t
  :custom
  (numpydoc-insert-examples-block nil)
  (numpydoc-template-long nil)
  :config
  (local-leader-keys
    :keymaps 'python-mode-map
    "n" '(numpydoc-generate :wk "Generate docstring")))
#+end_src

*** Pyenv-mode

~pyenv-mode~ is used to (de)activate pyenv environments via ~pyenv-mode-set~ and ~pyenv-mode-unset~. This allows us to start a REPL or Jupyter (org) notebook in the correct environment.

#+begin_src emacs-lisp
;; (use-package pyenv-mode
;;   :ensure t)
#+end_src

*** conda

Although I prefer to use poetry/pyenv to manage my Python coding projects and environments, on most of my computers I also have conda installed. There are a few use cases where this makes sense:

- Other people I work with use conda only and not poetry.
- I'm trying to clone a repository which uses conda to manage dependencies.
- I need to install a non-python package via conda.

Furthermore, poetry is actually set up in a way to be able to use with conda as an environment manager (see [[https://github.com/python-poetry/poetry/blob/master/src/poetry/utils/env.py#L675][here]]). See also more info on this [[https://stackoverflow.com/questions/70851048/does-it-make-sense-to-use-conda-poetry][StackOverflow post]].

#+begin_src emacs-lisp
(use-package conda
  :ensure t
  :defer t)
#+end_src

*** Python development workflow with Poetry

Currenly I prefer the following workflow (which seems to work... most of the time):

1) Create a new poetry project via =poetry init= or =poetry new=.
2) =git init= the project root folder.
3) Create a ~.envrc~ file with =layout pyenv {version}= and =layout poetry= in it.
4) Begin to add dependencies via =poetry add= (=-D= switch for developer dependencies).
5) Create a =pyrightconfig.json= in the project root, and set the ~venvPath~ and ~venv~ variables accordingly.
   
This has the following benefits compared to other things I tried:
- Don't need to use =poetry-tracking-mode=, which can be slow in my experience.
- Creates replicable configs across machines.

** Jupyter

#+begin_src emacs-lisp
(use-package jupyter
  :ensure t
  :bind (:map jupyter-repl-mode-map 
              ("C-j" . 'jupyter-repl-forward-cell)
              ("C-k" . 'jupyter-repl-backward-cell))
  :init
  (org-babel-jupyter-override-src-block "python")
  :custom
  (org-babel-default-header-args:jupyter-python '((:async . "yes")
                                                  (:session . "py")
                                                  (:kernel . "python3"))))
#+end_src

See also [[https://orgmode.org/manual/Using-Header-Arguments.html][here]] for more info on how to use ~header-args~ properties in org files.

** AutoHotKey

#+begin_src emacs-lisp
(when duy/is-wsl
  (use-package ahk-mode
    :ensure t))
#+end_src

* PDF

#+begin_src emacs-lisp
(defun duy/pdf-occur-view-next ()
  "View next pdf-occur match from pdf-occur-buffer"
  (interactive)
  (evil-next-visual-line)
  (pdf-occur-view-occurrence))


(defun duy/pdf-occur-view-prev ()
  "View previous pdf-occur match from pdf-occur-buffer"
  (interactive)
  (evil-previous-visual-line)
  (pdf-occur-view-occurrence))
#+end_src

#+begin_src emacs-lisp
(use-package pdf-tools
  :ensure t
  :init
  (pdf-tools-install)
  :bind (:map pdf-occur-buffer-mode-map
              ("C-<return>" . pdf-occur-view-occurrence)
              ("C-j" . duy/pdf-occur-view-next)
              ("C-k" . duy/pdf-occur-view-prev)
              :map pdf-view-mode-map
              ("C-s" . pdf-occur))
  :hook
  (pdf-view-mode-hook . evil-collection-pdf-setup))

;; pdf-view-restore remembers last position in pdf before closing

(use-package pdf-view-restore
  :ensure t
  :after pdf-tools
  :hook
  (pdf-view-mode-hook . pdf-view-restore-mode)
  :custom
  (pdf-view-restore-file-name (expand-file-name ".pdf-view-restore" user-emacs-directory))) 
#+end_src

* Ledger

#+begin_src emacs-lisp
(when (string= system-name "Duys-MBP.home")
  (use-package ledger-mode
    :ensure t
    :custom
    (ledger-reports '(("Balance (EUR)" "%(binary) -f %(ledger-file) bal --exchange EUR --price-db .pricedb Assets Liabilities")
                      ("Balance (MV)" "%(binary) -f %(ledger-file) bal -V --price-db .pricedb Assets Liabilities")
                      ("bal" "%(binary) -f %(ledger-file) bal --price-db .pricedb")
                      ("reg" "%(binary) -f %(ledger-file) reg --price-db .pricedb")))
    :init
    (add-to-list 'auto-mode-alist '("\\.pricedb\\'" . ledger-mode))
    :config
    (local-leader-keys
      :keymaps '(ledger-mode-map ledger-report-mode-map)
      "r" '(ledger-report :wk "Report")
      "a" '(ledger-add-transaction :wk "Add transaction")
      "e" '(ledger-report-edit-report :wk "Edit report")
      "g" '(ledger-report-goto :wk "Go to report")
      "s" '(ledger-report-save :wk "Save report"))
    (general-define-key
     :states '(normal motion override)
     :keymaps '(ledger-report-mode-map)
     "q"  'ledger-report-quit
     "r"  'ledger-report-redo)))
#+end_src

